### ISSUE TITLE
classic javascript syntax style

### ISSUE THREAD

**Issue by xuatz** [stickyfishes/psychobabble-reborn#11]
Is it a conscious decision to use the classic javascript syntax as opposed to ES2015++?

Just curious to know if its because ES2015++ syntax does not make sense in a typescript environment or that there are technical reasons to not adopt it.

While i cant really give any crazy performance benefits examples, personally for me there are some QOL of life improvements. It doesnt take any additional effort as well as Node 7 already [support a lot of the new syntax](http://node.green/) without any transpiling or turning on any flags.

**update 1**
actually i saw some new syntax already used, my question now evaporates to simply why `var` instead of `let` lol

**Comment by daryltanwk** [comment]
where do u see the code?

**Comment by xuatz** [comment]
some examples here
* https://github.com/stickyfishes/psychobabble-reborn/blob/master/frontend/src/test.ts#L16-L17
* https://github.com/stickyfishes/psychobabble-reborn/blob/master/backend/game/round.js#L11-L15

**Comment by daryltanwk** [comment]
im doing the /frontend side, and the test.ts is auto-generated by the angular CLI. as for my own code i haven't used any 'var' because my linter doesnt like it.

backend code written by soedy. have to ask him...

**Comment by soedar** [comment]
> Is it a conscious decision to use the classic javascript syntax as opposed to ES2015++?

Nope for the backend, probably a good idea to use let instead. Good call.

**Comment by daryltanwk** [comment]
~nothing else to do here~
